### PR TITLE
Update `not-` variants to support dynamic `group/` and `peer/` variants

### PR DESCRIPTION
**Pull request by brandonmcconnell**
I updated @MichaelAllenWarner's `not-` variant impl top support Tailwind's dynamic `group/` and `peer/` variants, introduced in Tailwind v3.2.

The main PR by @MichaelAllenWarner can be found here: https://github.com/tailwindlabs/tailwindcss/pull/7976

### CODE REVIEW

**Comment by brandonmcconnell** [comment]
@MichaelAllenWarner @RobinMalfait When I run the test suites using `npm run build && npm test`, I see the following failure(s):

```
Cannot find module '@tailwindcss/oxide' from 'src/lib/expandTailwindAtRules.js'

...

Test Suites: 64 failed, 23 passed, 87 total
Tests:       324 passed, 324 total
Snapshots:   0 total
Time:        3.502 s
Ran all test suites.
```

Is there another process I need to run for that Rust process to be analyzed?

---

### Screenshot

image

**Comment by MichaelAllenWarner** [comment]
@brandonmcconnell 

Thanks for this. I'm quite busy at the moment; not sure when I'll have a chance to take a closer look.

**Comment by MichaelAllenWarner** [comment]
@brandonmcconnell

I was able to get past the `oxide`-related errors by first installing Rust, following the instructions [here](https://www.rust-lang.org/tools/install), and then doing `npm run build:oxide` before trying `npm run test` again.

**Comment by brandonmcconnell** [comment]
Thanks @MichaelAllenWarner. That helped a ton.

I was able to diagnose the cause of the test failures. It as simply the order of the selectors.

Previously, the order was this:
* 🔴 `not-hover`
* 🔵 `group-not-hover`
* 🟠 `peer-not-hover`
* 🔴 `hover`
* 🔵 `group-hover`
* 🟠 `peer-hover`

But with my recent changes, it is now this:
* 🔴 `not-hover`
* 🔴 `hover`
* 🔵 `group-not-hover`
* 🔵 `group-hover`
* 🟠 `peer-not-hover`
* 🟠 `peer-hover`

This should still suffice for the same lower specificity for the `not-` counterparts of each of the three, and may even be arguably easier to manage.

All tests now pass — resolved in [commit ea22565](https://github.com/MichaelAllenWarner/tailwindcss/pull/6/commits/ea22565422bd15943e3411a90d90e54d2ad64e37)

**Comment by brandonmcconnell** [comment]
I added support for the following in [commit 977505e](https://github.com/MichaelAllenWarner/tailwindcss/pull/6/commits/977505ee91678df9a6762ed5139708f236e5df5c):

<table>
<thead><tr>
<th>Non-<code>not</code> variants</th>
<th><code>not</code> variants (new)</th>
</thead><tbody valign="top">
<tr>
<td><pre>supports-</pre></td>
<td><pre>not-supports-</pre></td>
</tr>
<tr></tr>
<tr>
<td><pre>aria-</pre></td>
<td><pre>
not-aria-
group-not-aria-
peer-not-aria-
</pre></td>
</tr>
<tr></tr>
<tr>
<td><pre>data-</pre></td>
<td><pre>
not-data-
group-not-data-
peer-not-data-
</pre></td>
</tr>
<tr></tr>
<tr>
<td><pre>dark</pre></td>
<td><pre>light</pre><em>**explanation/rationale below</em></td>
</tr>
<tr></tr>
<tr>
<td><pre>print</pre></td>
<td><pre>screen</pre><em>**explanation/rationale below</em></td>
</tr>
</tbody></table>

**Comment by brandonmcconnell** [comment]
I've also added tests for all of these new variants (and those missing, e.g. `aria-`, `data-`) via [commit 314f566](https://github.com/MichaelAllenWarner/tailwindcss/pull/6/commits/314f566427cd7f8159018d95870a083c306239e9).

@RobinMalfait If you could also check these tests, that would be a great help. Thank you.

cc @adamwathan @MichaelAllenWarner

**Comment by MichaelAllenWarner** [comment]
@brandonmcconnell 

Wow, thanks for all the work here!

I suspect that some of this will still require some discussion (assuming that the Tailwind team is indeed interested in adding this feature):

-  _Which_ of the core variants should get the `not-` treatment? (IMO you've chosen well.)
- Are the variants registered in the "right" order? Let's suppose that the order we were leaning toward in https://github.com/tailwindlabs/tailwindcss/pull/7976 is correct. In that case, it looks to me like this PR has the right ordering _within_ each "section" (i.e., the pseudo-class variants are in the right order, the aria-variants are in the right order, etc.)—but would that suffice, or would we need the ordering to apply across all sections? What I mean is: do we need to register _all_ the `not-` variants before registering their non-`not-` counterparts (and perhaps even before _all_ other variants)? If so, there'd be need for some rather significant refactoring.

Small bug I noticed: you're using `group-aria-not-` and `peer-aria-not-` instead of `group-not-aria-` and `peer-not-aria-` in your tests.

**Comment by brandonmcconnell** [comment]
@MichaelAllenWarner Sure thing. Thanks for all the feedback and testing and so quickly.

I'll fix that `x-aria-not` vs. `x-not-aria` typo asap.

Giving it some more thought, I can fathom some decent reasoning for registering all the `not` variants first.

It may not matter at all, but maybe, in this case it would…

`not-hover` ➞ `hover` ➞ `not-focus` ➞ `focus`

In stacking contexts, what would happen if someone used `hover:not-focus:_`? I think that would still be lower specificity than `hover:focus:_` so it would override as expected. Are there cases where it might not? We might be fine leaving this as is, but I'm trying to think of a scenario where the ordering might cause a mixup in intended specificity. Do you know of any?

One more question— should we also adjust the `addVariant` and `matchVariant` functions so that they automatically add a `not-` counterpart for any custom variants added, or should that always be manual and up to the user? I'm inclined to let the user handle that manually, especially as catching such a thing automatically would require several checks such as whether the custom variant being added needs a `not` added to a query statement (e.g. `@media not`) or wrapped in a `:not` pseudo (e.g. `:not(&)`).

**Comment by MichaelAllenWarner** [comment]
@brandonmcconnell

Oh, right: you've actually _deviated_ from the ordering that was discussed in https://github.com/tailwindlabs/tailwindcss/pull/7976. If you read the conversation there, you'll see that we came to the tentative conclusion that `not-` variants should be registered before non-`not-` variants, so that the non-`not-` utilities come later in the CSS and therefore win specificity-battles over `not-` utilities when there's a tie.

So I think it's best if you undo your re-ordering of `tests/variants.test.css` and instead refactor `src/corePlugins.js` to preserve the registration-order that I was using:

* 🔴 `not-hover`
* 🔵 `group-not-hover`
* 🟣 `peer-not-hover`
* 🔴 `hover`
* 🔵 `group-hover`
* 🟣 `peer-hover`

> In stacking contexts, what would happen if someone used `hover:not-focus:_`? I think that would still be lower specificity than `hover:focus:_` so it would override as expected.

I believe this would actually be one of those specificity _ties_ I mentioned above, and the "winner" would be whichever class is declared later in the CSS (which I think would be the `hover:focus:_` class if the `not-focus:` variant is registered before the `focus:` variant).

What I was getting at in my previous comment was: would it be enough to use this `not`-first ordering within each "section" (i.e., among the pseudo-class variants, and among the aria-variants, etc.)? or would _all_ `not-` variants need to be declared first (so that, say, `not-aria-hidden:` is registered before `focus:`)?

> One more question— should we also adjust the `addVariant` and `matchVariant` functions so that they automatically add a `not-` counterpart for any custom variants added, or should that always be manual and up to the user? I'm inclined to let the user handle that manually, especially as catching such a thing automatically would require several checks such as whether the custom variant being added needs a `not` added to a query statement (e.g. `@media not`) or wrapped in a `:not` pseudo (e.g. `:not(&)`).

That's an interesting idea, but I'd save it for another PR down the road (if the basic `not-` variants gets added).

**Comment by brandonmcconnell** [comment]
@MichaelAllenWarner Thanks for clarifying! Re this comment:

>What I was getting at in my previous comment was: would it be enough to use this not-first ordering within each "section" (i.e., among the pseudo-class variants, and among the aria-variants, etc.)? or would all not- variants need to be declared first (so that, say, not-aria-hidden: is registered before focus:)?

That was my thinking in how I did my reordering. Technically, all the `not` pseudos appear before their non-`not` counterparts, so I think the end result would be the same, but I am not 100% sure. If that is indeed the case, I think this would still uphold the agreed-upon ordering from your PR https://github.com/tailwindlabs/tailwindcss/pull/7976 and the non-`not` variants would still always trump the `not` variants.

With all of that in mind, I'll investigate to see if there's a simple way to achieve putting all the `not` variants first.

**Comment by MichaelAllenWarner** [comment]
@brandonmcconnell 

> That was my thinking in how I did my reordering. Technically, all the not pseudos appear before their non-not counterparts, so I think the end result would be the same, but I am not 100% sure.

Well, I think it's not _just_ about a non-`not-` variant trumping its direct `not-` counterpart (e.g., `hover:` trumping `not-hover:`). It's also about `hover:` trumping `not-focus:`, and maybe(?) even `aria-hidden:` and `data-[foo]:` trumping `not-focus:`, etc. (Sorry if I'm over-explaining at this point; just want to make sure that we're on the same page.)

> With all of that in mind, I'll investigate to see if there's a simple way to achieve putting all the not variants first.

Definitely feel free, although you might want to wait for the input of Adam or Robin.

Regardless, I don't have much time right now to work on this stuff, and I appreciate what you've been doing here.

**Comment by brandonmcconnell** [comment]
@MichaelAllenWarner Thanks again for clarifying. That makes perfect sense.

I'm totally down to adjust my implementation to account for that new sort-order. I think I'll wait to hear back from @adamwathan or @RobinMalfait, only because—as I see it—we have two options to achieve that:
* I can manually change the order and simply add all the `not` variants first.
  
  Easy, but it doesn't allow users to add their own `not` variants in the same way.
* We add a new CSS/tailwind layer exclusively for `not` variants so that users can take full advantage of this feature.
  
  I could use a bit more background on how the `@tailwind` layers are setup/config'd so that I can add a custom one for this. I think this would likely require with its own dedicated `addNotVariant` and `matchNotVariant` helper functions, or something to that effect.
  
  For any added directly to the CSS via `@layer variants`, I'm thinking we could use either ref a new layer `notVariants` which is probably the simplest way to go, or we can use a nested layer within the existing `variants` layer called `not` which could then be ref'd as `@layer variants.not`. I've gone back-and-forth on which impl I like better personally, and I'm totally indifferent now. Either one would work great imo and allow the user to add their one `not` variants and use them effectively.

---

@adamwathan & @RobinMalfait any thoughts here?

**Comment by MichaelAllenWarner** [comment]
@brandonmcconnell Closing this, since the main PR was closed also. Thanks again for working on this, though.

**Comment by brandonmcconnell** [comment]
@MichaelAllenWarner It was a pleasure. Until next time 🙂

**Pull request closed without merging**
